import datetime
print(datetime.datetime.now())
print(datetime.date.today())
print(datetime.datetime.now().year)
print(datetime.datetime.now().month)
print(datetime.datetime.now().day)
print(datetime.datetime.now().hour)
print(datetime.datetime.now().minute)
print(datetime.datetime.now().second)
print(datetime.datetime.now().microsecond)
print(datetime.datetime.now().timestamp)
print(datetime.datetime.now().date())
print(datetime.datetime.now().time())
print(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print(datetime.datetime.now().strftime("%A, %B %d, %Y"))
print(datetime.datetime.now().strftime("%I:%M %p"))
print(datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S.%fZ"))
print(datetime.datetime.now().isoformat())
print(datetime.datetime.now().fromtimestamp(0))
print(datetime.datetime.now().timetz())
print(dir(datetime))
import datetime as dt
start_time=dt.datetime.now()
start_time.replace(month=12,day=25)
from datetime import *
today=date.today()
print(today)